const DEMO_DATA = [
  ['2026-08-20','MLB-10001','Fone Bluetooth Pro',2,149.9,'Mercado Livre'], ['2026-08-20','MLB-10002','Suporte Articulado para Monitor',1,189.9,'Mercado Livre'],
  ['2026-08-21','MLB-10003','Fone Bluetooth Pro',1,149.9,'Mercado Livre'], ['2026-08-21','MLB-10004','Teclado Mecânico Compacto',2,229.9,'Mercado Livre'],
  ['2026-08-22','MLB-10005','Suporte Articulado para Monitor',3,189.9,'Mercado Livre'], ['2026-08-23','MLB-10006','Fone Bluetooth Pro',1,149.9,'Mercado Livre'],
  ['2026-08-24','MLB-10007','Teclado Mecânico Compacto',1,229.9,'Mercado Livre'], ['2026-08-25','MLB-10008','Webcam Full HD',2,179.9,'Mercado Livre'],
  ['2026-08-26','MLB-10009','Fone Bluetooth Pro',4,149.9,'Mercado Livre'], ['2026-08-27','MLB-10010','Webcam Full HD',1,179.9,'Mercado Livre']
].map(([date,orderId,product,quantity,unitPrice,channel]) => ({ date, orderId, product, quantity, unitPrice, total: quantity * unitPrice, channel }));

let sales = []; let charts = {};
const money = new Intl.NumberFormat('pt-BR', { style:'currency', currency:'BRL' });
const number = new Intl.NumberFormat('pt-BR');
const qs = (s) => document.querySelector(s);
const normalize = (s='') => String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/g, '');
const aliases = { date:['data','datadavenda','datafechamento','dateclosed','datecreated','date'], orderId:['pedido','numerodopedido','idpedido','orderid','idordem','venda'], product:['produto','titulo','anuncio','itemtitle','descricao','product'], quantity:['quantidade','unidades','quantity','qtd'], unitPrice:['precounitario','preco','valorunitario','unitprice','price'], total:['total','valortotal','valorvenda','receita','totalamount','amount'], channel:['canal','origem','channel','site'] };

function columnFor(headers, key) { return headers.findIndex(h => aliases[key].includes(normalize(h))); }
function asNumber(v) { if (typeof v === 'number') return v; const t = String(v ?? '').trim().replace(/R\$|\s/g,'').replace(/\./g,'').replace(',','.'); return Number(t) || 0; }
function asDate(v) { if (v instanceof Date && !isNaN(v)) return v.toISOString().slice(0,10); if (typeof v === 'number' && window.XLSX) { const d = XLSX.SSF.parse_date_code(v); return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`; } const s = String(v ?? '').trim(); const br = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/); if (br) return `${br[3]}-${br[2].padStart(2,'0')}-${br[1].padStart(2,'0')}`; const d = new Date(s); return isNaN(d) ? '' : d.toISOString().slice(0,10); }

function mapRows(rows) { const headers = rows[0].map(x => String(x ?? '')); const col = Object.fromEntries(Object.keys(aliases).map(k => [k, columnFor(headers,k)])); if (col.date < 0 || col.product < 0 || (col.total < 0 && col.unitPrice < 0)) throw new Error('Não encontrei as colunas essenciais. Use Data, Produto e Total (ou Preço).'); return rows.slice(1).map((row,i) => { const quantity = col.quantity >= 0 ? asNumber(row[col.quantity]) || 1 : 1; const unitPrice = col.unitPrice >= 0 ? asNumber(row[col.unitPrice]) : 0; const total = col.total >= 0 ? asNumber(row[col.total]) : unitPrice * quantity; return { date:asDate(row[col.date]), orderId:col.orderId >= 0 ? String(row[col.orderId] ?? '') : `Linha ${i+2}`, product:String(row[col.product] ?? 'Sem nome'), quantity, unitPrice:unitPrice || total / quantity, total, channel:col.channel >= 0 ? String(row[col.channel] ?? 'Mercado Livre') : 'Mercado Livre' }; }).filter(s => s.date && s.total > 0); }
function filtered() { const from=qs('#date-from').value, to=qs('#date-to').value, product=qs('#product-filter').value; return sales.filter(s => (!from || s.date >= from) && (!to || s.date <= to) && (!product || s.product === product)); }
function updateProductOptions() { const select=qs('#product-filter'), current=select.value; const products=[...new Set(sales.map(s=>s.product))].sort(); select.innerHTML='<option value="">Todos os produtos</option>'+products.map(p=>`<option>${escapeHtml(p)}</option>`).join(''); select.value=current; }
function escapeHtml(value) { const d=document.createElement('div'); d.textContent=value; return d.innerHTML; }
function render() { const data=filtered(); const revenue=data.reduce((a,s)=>a+s.total,0), units=data.reduce((a,s)=>a+s.quantity,0), orders=new Set(data.map(s=>s.orderId)).size, ticket=orders ? revenue/orders : 0; qs('#metric-revenue').textContent=money.format(revenue); qs('#metric-orders').textContent=number.format(orders); qs('#metric-units').textContent=number.format(units); qs('#metric-ticket').textContent=money.format(ticket); const dates=data.map(s=>s.date).sort(); qs('#period-label').textContent=dates.length ? `${new Date(dates[0]+'T12:00').toLocaleDateString('pt-BR')} a ${new Date(dates.at(-1)+'T12:00').toLocaleDateString('pt-BR')}` : 'Nenhum registro para os filtros selecionados'; qs('#metric-revenue-detail').textContent=`${number.format(units)} itens vendidos`; qs('#metric-orders-detail').textContent=`${number.format(orders)} pedidos únicos`; qs('#metric-units-detail').textContent=`em ${number.format(orders)} pedidos`; qs('#metric-ticket-detail').textContent='por pedido'; renderCharts(data); renderTables(data); }
function renderCharts(data) { const daily={}; data.forEach(s => daily[s.date]=(daily[s.date]||0)+s.total); const labels=Object.keys(daily).sort(); const channel={}; data.forEach(s => channel[s.channel]=(channel[s.channel]||0)+s.total); for (const chart of Object.values(charts)) chart.destroy(); charts.daily=new Chart(qs('#daily-chart'),{type:'line',data:{labels:labels.map(d=>new Date(d+'T12:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})),datasets:[{data:labels.map(d=>daily[d]),borderColor:'#3483fa',backgroundColor:'rgba(52,131,250,.10)',fill:true,tension:.35,pointRadius:3,pointBackgroundColor:'#3483fa'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>money.format(c.raw)}}},scales:{y:{ticks:{callback:v=>'R$ '+number.format(v)},grid:{color:'#eef1f5'}},x:{grid:{display:false}}}}}); charts.channel=new Chart(qs('#channel-chart'),{type:'doughnut',data:{labels:Object.keys(channel),datasets:[{data:Object.values(channel),backgroundColor:['#ffe600','#3483fa','#00a650','#9b59b6','#ff7b54'],borderWidth:0,hoverOffset:4}]},options:{responsive:true,maintainAspectRatio:false,cutout:'69%',plugins:{legend:{position:'bottom',labels:{boxWidth:10,padding:16,font:{family:'DM Sans'}}},tooltip:{callbacks:{label:c=>`${c.label}: ${money.format(c.raw)}`}}}}}); }
function renderTables(data) { const products={}; data.forEach(s=>{products[s.product]??={quantity:0,total:0}; products[s.product].quantity+=s.quantity;products[s.product].total+=s.total;}); const p=Object.entries(products).sort((a,b)=>b[1].total-a[1].total).slice(0,8); qs('#products-table').innerHTML=p.length?p.map(([name,v])=>`<tr><td class="product-name" title="${escapeHtml(name)}">${escapeHtml(name)}</td><td>${number.format(v.quantity)}</td><td>${money.format(v.total)}</td></tr>`).join(''):'<tr><td class="empty" colspan="3">Sem vendas no período</td></tr>'; const recent=[...data].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8); qs('#orders-table').innerHTML=recent.length?recent.map(s=>`<tr><td>${new Date(s.date+'T12:00').toLocaleDateString('pt-BR')}</td><td>${escapeHtml(s.orderId)}</td><td class="product-name" title="${escapeHtml(s.product)}">${escapeHtml(s.product)}</td><td>${money.format(s.total)}</td></tr>`).join(''):'<tr><td class="empty" colspan="4">Sem pedidos no período</td></tr>'; }
function setSales(rows, source) { sales=rows; const dates=sales.map(s=>s.date).sort(); qs('#date-from').value=dates[0]||''; qs('#date-to').value=dates.at(-1)||''; updateProductOptions(); qs('#source-notice').classList.toggle('live',source!=='demo'); qs('#source-notice').lastElementChild.textContent=source==='demo'?'Dados de demonstração. Importe seu Excel para começar.':`${number.format(sales.length)} linhas carregadas · ${source}`; render(); }
function toast(message) { const t=qs('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000); }
async function importFile(file) { try { const buffer=await file.arrayBuffer(); const wb=XLSX.read(buffer,{type:'array',cellDates:true}); const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''}); const imported=mapRows(rows); if (!imported.length) throw new Error('A planilha não contém vendas válidas.'); localStorage.setItem('ml-sales',JSON.stringify(imported)); setSales(imported,`importado de ${file.name}`); toast('Planilha importada com sucesso.'); } catch(e) { toast(e.message || 'Não foi possível ler a planilha.'); } }
async function loadCloud() { try { const res=await fetch('data/vendas.json',{cache:'no-store'}); if (!res.ok) throw new Error(); const json=await res.json(); if (!Array.isArray(json.sales) || !json.sales.length) throw new Error(); setSales(json.sales,`atualizado em ${new Date(json.updatedAt).toLocaleString('pt-BR')}`); toast('Dados atualizados.'); } catch { const stored=localStorage.getItem('ml-sales'); if(stored) { setSales(JSON.parse(stored),'importação salva neste navegador'); toast('Usando sua última importação.'); } else { setSales(DEMO_DATA,'demo'); toast('Ainda não há dados sincronizados.'); } } }
document.addEventListener('DOMContentLoaded',()=>{ qs('#file-input').addEventListener('change',e=>e.target.files[0]&&importFile(e.target.files[0])); ['#date-from','#date-to','#product-filter'].forEach(s=>qs(s).addEventListener('change',render)); qs('#clear-filters').addEventListener('click',()=>{qs('#date-from').value='';qs('#date-to').value='';qs('#product-filter').value='';render();});qs('#load-cloud').addEventListener('click',loadCloud); loadCloud(); });

